/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:4828f761-2128-4e03-a128-5780f6824ac3",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_86RYYYWln",
    "aws_user_pools_web_client_id": "478l8dbu2mfd0hbjecf4ifkmhe",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "amptool",
            "endpoint": "https://s8b795ky1j.execute-api.ap-northeast-2.amazonaws.com/dev",
            "region": "ap-northeast-2"
        }
    ]
};


export default awsmobile;
